language: python

cache: pip

python:
  - "2.7"
  - "3.6"

matrix:
    fast_finish: true
    include:
    - python: 3.7
      sudo: required
      dist: xenial
    - python: 3.8-dev
      sudo: required
      dist: xenial
    allow_failures:
    - python: 3.8-dev

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt

script:
  - cd python && python setup.py develop test
